name: Code linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir external_tools
        cd external_tools
        git clone https://github.com/ioannis-vm/AZ_pelicun
        cd AZ_pelicun
        git checkout bc9ae2b7
        python -m pip install -e .
        cd ../../
    - name: Analyze the code with pylint
      run: |
        pylint src
    - name: Analyze the code with flake8
      run: |
        flake8 src
